version: '3.4'

services:
  gameconnectdots:
    image: gameconnectdots
    # command: ["bash -c 'npm install && npm run start-docker-dev'"]
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    # volumes:
    #   - .:/app
    # hostname: frontend-localhost.domain.com
     
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
