version: '3.4'

services:
  gameconnectdots:
    image: gameconnectdots
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
